---
title: 시각화
author: "Nougaga"
date: 2020-08-06
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(max.print=10)
```
```{r}
library(mlbench)
data(Ozone)
ozo <- Ozone
```

### **시각화**

#### 1. plot: 기본은 산점도

```{r Ozone}
plot(ozo$V8,ozo$V9)

# 그래프 꾸미기
# ?plot
plot(ozo$V8,ozo$V9,
     xlab='Sandburg Temp',ylab='El Monte Temp')
```

  + par(): 그래프 여러 개를 나누어 그릴 수 있는 분할공간

```{r par}
# ?par
par(mfrow=c(1,2), pty="s")
plot(ozo$V8,ozo$V9,
     xlab='Sandburg Temp',ylab='El Monte Temp',
     pch=20, cex=0.5)
plot(ozo$V8,ozo$V9,
     xlab='Sandburg Temp',ylab='El Monte Temp',
     pch="+", cex=0.7)
```

```{r cars}
plot(cars, type='l')
par(mfrow=c(1,2), pty="s")
plot(cars, type='b')
plot(cars, type='o')
```

  + jitter(): 데이터에 약간의 노이즈를 추가해줌

```{r jitter}
tail(ozo[,c("V6","V7")],10)

par(mfrow=c(1,2), pty="s")
plot(ozo$V6,ozo$V7,
     xlab="Wind speed",ylab="Humidity",
     pch=15,cex=.5)
plot(jitter(ozo$V6),jitter(ozo$V7),
     xlab="Wind speed",ylab="Humidity",
     pch=15,cex=.5)

```

  + points(): 이미 생성된 plot() 위에 점을 추가로 그려줌
  
```{r points}
data(iris)
with(iris,{
  plot(NULL,xlim=c(0,5),ylim=c(0,10),
       xlab='width',ylab='length',
       main='iris',type='n')  # 빈 plot 공간만 그림 (점은 아래에서 찍음)
  points(Sepal.Width,Sepal.Length,cex=1,pch="*",col='blue')
  points(Petal.Width,Petal.Length,cex=1,pch="+",col='red')  
})

```

  + lines(): 꺾은선 
  
```{r lines}
x <- seq(0,2*pi, 0.1)
y <- sin(x)
plot(x, y, cex=0.5, col='red')
lines(x,y)
```

  + abline(): 직선
    + y=ax+b, y=h, x=v 등의 직선을 그래프 위에 그릴 수 있다.
    + 추세선, 보조선, 사분면 분할, ...
  
```{r abline}
plot(cars, xlim=c(0,25));abline(a=-5,b=3.5,col='red')

plot(cars, xlim=c(0,25))
abline(a=--10, b=3.2, col='purple')
abline(h=mean(cars$dist), lty=2, col='gray')
abline(v=mean(cars$speed), lty=2, col='light gray')
```

  + curve(): 곡선
  
```{r curve}
curve(cos, 0, 2*pi)
abline(v=pi, lty=15, col="light blue")
```

  + annotation 1) text()

```{r text}
plot(cars, cex=0.5)
text(cars$speed, cars$dist, pos=3, cex=0.5)
```

  + annotation 2) identify()
  
```{r identify}
plot(cars, cex=0.5)
identify(cars$speed, cars$dist)
```

  + legend(): 범례
  
```{r}
plot(iris$Sepal.Width, iris$Sepal.Length, pch=1,
     xlab="width", ylab="length", xlim=c(0,5), ylim=c(0,8))
points(iris$Petal.Width, iris$Petal.Length, pch="+", col="red")
legend("bottomright", legend=c("Sepal","Petal"), pch=c(1,43),
       col=c("black","red"),bg="gray")
```

  + boxplot()
  
```{r}
library(ggplot2)
mpg <- as.data.frame(ggplot2::mpg)
boxplot(mpg$hwy)

# 통계치도 출력
boxplot(mpg$hwy)$stats

# 12~37 벗어나면 NA 할당
mpg$hwy <- ifelse(mpg$hwy<12 | mpg$hwy>37, NA, mpg$hwy)
# 결측치 확인
table(is.na(mpg$hwy))

library(dplyr)
mpg %>% 
  group_by(drv) %>% 
  summarise(mean_hwy = mean(hwy, na.rm=T))
```

#### 2. scatterplot3d 패키지를 이용한 3차원 시각화

  + scatterplot3d(밑변,우변,좌변)

```{r scatterplot3d}
library(scatterplot3d)
iris_setosa <- iris[iris$Species == "setosa",]
iris_versicolor <- iris[iris$Species == "versicolor",]
iris_virginica <- iris[iris$Species == "virginica",]

# 1. 3차원 프레임(틀) 생성
iris_d3 <- scatterplot3d(iris$Petal.Length, 
                         iris$Sepal.Length, 
                         iris$Sepal.Width,
                         type="n", angle=30)

# 2. 산점도 시각화
iris_d3$points3d(iris_setosa$Petal.Length,
                 iris_setosa$Sepal.Length,
                 iris_setosa$Sepal.Width,
                 bg="red", pch=21)

iris_d3$points3d(iris_setosa$Petal.Length,
                 iris_setosa$Sepal.Length,
                 iris_setosa$Sepal.Width,
                 bg="blue", pch=23)

iris_d3$points3d(iris_setosa$Petal.Length,
                 iris_setosa$Sepal.Length,
                 iris_setosa$Sepal.Width,
                 bg="green", pch=25)
```




